export const CONTACT_LIST = 'contacts'
export const CONTACT_CREATE = 'create'
export const CONTACT_INFO = 'info'
export const SETTINGS = 'settings'
export const LOGIN = 'login'
export const REGISTER = 'register'
export const HOME_NAVIGATOR = 'HOME_NAVIGATOR'
