export const CONTACT_LIST = '首页'
export const CONTACT_CREATE = '创建联系人'
export const CONTACT_INFO = '信息'
export const SETTINGS = '设置'
export const LOGIN = '登录'
export const REGISTER = '注册'
export const HOME_NAVIGATOR = 'HOME_NAVIGATOR'
